### ISSUE TITLE
Linker Tools Error vdb_render

### ISSUE THREAD

**Issue by jonassorgenfrei** [AcademySoftwareFoundation/openvdb#496] opened 2019-08-03 13:25 UTC
Hey,

I've got compilation complications when trying to compile vdb_render for Windows 10.

Error LNK2019 Reference to undefined symbol ""private: static union half::uif const * const half::_toFloat" (?_toFloat@half@@0QBTuif@1@B)" in Funktion ""public: static void __cdecl openvdb::v6_2::io::HalfReader<1,float>::read(class std::basic_istream<char,struct std::char_traits<char> > &,float *,unsigned int,unsigned int,class openvdb::v6_2::io::DelayedLoadMetadata *,unsigned __int64)" (?read@?$HalfReader@$00M@io@v6_2@openvdb@@SAXAEAV?$basic_istream@DU?$char_traits@D@std@@@std@@PEAMIIPEAVDelayedLoadMetadata@234@_K@Z)".	vdb_render	D:\Bibliotheken\openvdb\build\openvdb\cmd\openvdb_render.obj	1	

I'm not quite sure if it's a general problem or just a wrong setup in my system.

Best
Jonas

**Comment by jonassorgenfrei** [comment] 2019-08-03 14:12
The error seems to come from line 343 in io/Compression.h.
When I comment the std::copy out it compiles and seems to work, but since I just started diving into openvdb im not quit sure what may can go wrong internally, when this copy to the data parameter ist missing.

**Comment by danrbailey** [comment] 2019-08-12 20:10
This has been raised before - https://github.com/AcademySoftwareFoundation/openvdb/issues/247

That thread should offer some explanation as to why it's happening. I was under the impression that this issue has since been resolved by the CMake refactor, but please do let us know if that's not the case (I'm not a Windows user).

**Comment by jonassorgenfrei** [comment] 2019-08-12 23:11
Well it's not the same error as mentioned in the thread. 
I double checked that the HALF_EXPORTS wasn't set in the the project.

It seems to be a problem in the Half-2_3.lib. 
Linking against the static lib (Half-2_3_static.lib) worked fine, only the dynamic lib produced problems,

**Comment by Idclip** [comment] 2019-08-22 18:27
@danrbailey our appveyor CI is caching the build dir and seems to be content with keeping openexr at 2.2. I think 2.3 now exists in vcpkg - perhaps we could try that?

**Comment by danrbailey** [comment] 2019-11-12 22:53
I have reproduced the issue and found a fix - https://github.com/AcademySoftwareFoundation/openvdb/pull/550

Thanks for reporting.

**Comment by danrbailey** [comment] 2019-11-27 21:29
This fix has now been merged in, closing out this issue.

**Closed by danrbailey** 2019-11-27 21:29 UTC
