### ISSUE TITLE
Which is the latest working TBB for OpenVDB 3.0.0?

### ISSUE THREAD

**Issue by obfuscated** [AcademySoftwareFoundation/openvdb#152] opened 2017-05-11 12:26 UTC
We're using OpenVDB 3.0.0 on Linux.
I'm trying to update our TBB implementation to 2017 update 5, but there is one pretty bad crash when we try to open a vdb and read its content.

If I revert the version of TBB the problem disappears.
Below you can find the backtrace printed by valgrind:

> ==26566== Process terminating with default action of signal 11 (SIGSEGV)
==26566==  Access not within mapped region at address 0x10
==26566==    at 0x114E587A: load_with_acquire (tbb_machine.h:611)
==26566==    by 0x114E587A: __TBB_load_with_acquire<tbb::interface5::internal::hash_map_base::node_base*> (tbb_machine.h:706)
==26566==    by 0x114E587A: itt_load_word_with_acquire<tbb::interface5::internal::hash_map_base::node_base*> (tbb_profiling.h:209)
==26566==    by 0x114E587A: acquire (concurrent_hash_map.h:647)
==26566==    by 0x114E587A: bucket_accessor (concurrent_hash_map.h:642)
==26566==    by 0x114E587A: tbb::interface5::concurrent_hash_map<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool, tbb::tbb_hash_compare<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*>, tbb::tbb_allocator<std::pair<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool> > >::lookup(bool, openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>* const&, bool const*, tbb::interface5::concurrent_hash_map<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool, tbb::tbb_hash_compare<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*>, tbb::tbb_allocator<std::pair<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool> > >::const_accessor*, bool, tbb::interface5::concurrent_hash_map<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool, tbb::tbb_hash_compare<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*>, tbb::tbb_allocator<std::pair<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool> > >::node* (*)(tbb::tbb_allocator<tbb::interface5::concurrent_hash_map<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool, tbb::tbb_hash_compare<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*>, tbb::tbb_allocator<std::pair<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool> > >::node>&, openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>* const&, bool const*), tbb::interface5::concurrent_hash_map<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool, tbb::tbb_hash_compare<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*>, tbb::tbb_allocator<std::pair<openvdb::v3_0_0::tree::ValueAccessorBase<openvdb::v3_0_0::tree::Tree<openvdb::v3_0_0::tree::RootNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::InternalNode<openvdb::v3_0_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > const>*, bool> > >::node*) (concurrent_hash_map.h:1132)
==26566==    by 0x114E61E4: insert (concurrent_hash_map.h:951)
==26566==    by 0x114E61E4: attachAccessor (Tree.h:1413)
==26566==    by 0x114E61E4: ValueAccessorBase (ValueAccessor.h:107)
==26566==    by 0x114E61E4: ValueAccessor3 (ValueAccessor.h:2089)
==26566==    by 0x114E61E4: ValueAccessor (ValueAccessor.h:479)
==26566==    by 0x114E61E4: getConstAccessor (Grid.h:593)

**Comment by obfuscated** [comment] 2018-06-25 18:40
Of course.

**Comment by danrbailey** [comment] 2019-11-12 22:52
Closing this as the minimum TBB dependency is now 2017 U6 so I assume the issue is now resolved. Re-open if not.

**Closed by danrbailey** 2019-11-12 22:52 UTC
