### ISSUE TITLE
[BUG] Error in some boost library function at build time which also appears on running as a standalone

### ISSUE THREAD

**Issue by ravikul505** [AcademySoftwareFoundation/openvdb#1604] opened 2023-03-29 15:32 UTC
### Environment
**Operating System:** (e.g. Windows )
**Version / Commit SHA:** (e.g VDB 10.0.0/10.0.01)
**Other:** (e.g compiler, C++ standard etc.)

### Describe the bug
(upon building with the latest version of boost this error appears at buid 

D:\openvdb-10.0.1\openvdb\openvdb\points/PointDataGrid.h(1407,109): error C2039: 'second': is not a member of 'std::pai
r<const std::string,boost::any>' [D:\openvdb-10.0.1\build\openvdb\openvdb\openvdb_shared.vcxproj])

### To Reproduce
1. Build with 'as given in openvdb github . i just followed those steps '

**Comment by Idclip** [comment] 2023-05-28 03:44
Hey @ravikul505,

This seems to be a duplicate of https://github.com/AcademySoftwareFoundation/openvdb/issues/1446. Comments on PRs associated with this indicate that updating VS2022 fixed the issue. Can you confirm what VS version you're building with and whether it's the latest? If not, try updating and building again

**Comment by Idclip** [comment] 2023-09-23 08:59
Closing as resolved, but please reopen if the above does not fix your issue

**Closed by Idclip** 2023-09-23 08:59 UTC
Labels: bug
