### ISSUE TITLE
[BUILD][ERROR]  VS 2022 with /permissive-

### ISSUE THREAD

**Issue by DevilDevShark** [AcademySoftwareFoundation/openvdb#1385] opened 2022-05-20 11:22 UTC
### Environment
**Operating System:** Windows 11
**Version / Commit SHA:** eb1cbad
**CMake Version:** 3.23.0

### Describe the problem

Hello,

I have a problem with this library and only this library.

```
#include <openvdb/tools/LevelSetFilter.h>
```

![image](https://user-images.githubusercontent.com/36869574/169506621-783ba1fe-486a-4149-b192-018ba56d2768.png)

I installed VCPKG then installed OpenVDB then manually.
I created an empty project then a CMake project with visual studio 2022 then tried to debug and compile.
I tried to compile separately with CMake.
I tested on another computer.
Nothing to do !

| Severity | Code  | Description                                                            | Project | File                                                            | Line |
| -------- | ----- | ---------------------------------------------------------------------- | ------- | --------------------------------------------------------------- | ---- |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1175 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1219 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1341 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1341 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1353 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1377 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1382 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1396 |
| Erreur   | C2039 | 'second' n'est pas membre de 'std::pair<const std::string,boost::any>' | test    | C:\Program Files\OpenVDB\include\openvdb\points\PointDataGrid.h | 1407 |

![image](https://user-images.githubusercontent.com/36869574/169506404-bcafa810-fc5c-4bcb-9262-54e7134fd0dd.png)

**Comment by e4lam** [comment] 2022-07-28 00:12
Confirmed, we get this with VS2022 as well.

The error doesn't make a lot of sense as clearly `std::pair` (of any type) should have a member named `second`. I tried adding `#include <utility>` to no avail.

In `points/PointDataGrid.h` around line 1175 we have:
```
            auto it = auxData.find(key);
            if (it != auxData.end()) {
                return *(boost::any_cast<compression::PagedInputStream::Ptr>(it->second));
```
where `auxData` is of type `AuxDataMap` defined as:
```
using AuxDataMap = std::map<std::string, boost::any>;
```
So the other odd thing here is that MSVC thinks the the key type is `const std::string` which as far as I can tell should be non-const.

**Comment by e4lam** [comment] 2022-07-28 03:27
It's very odd that I'm unable to reproduce with a fresh checkout using vcpkg for dependencies and VS 2022, doing a shared library build. The unit tests all build and seem to past. I tried locally modifying `vdb_print.cc` to the code above, as well as just including `<openvdb/points/PointDataGrid.h>`. That also failed to reproduce the error.

**Comment by e4lam** [comment] 2022-07-28 03:56
Reproduced! It requires the `/permissive-` MSVC compiler option. Changing `/std:c++14` (the default) to `/std:c++17` makes no difference wrt to the compiler errors.

**Comment by e4lam** [comment] 2022-07-28 14:08
It seems to be related to two phase lookup somehow as turning it off with `/permissive- /Zc:twoPhase-` will shut up the compiler errors. Also helping the compiler along of what the std pair type should be works around the issue as well.
eg.
```
@@ -1172,7 +1174,8 @@ PointDataLeafNode<T, Log2Dim>::readBuffers(std::istream& is, const CoordBBox& /*
             std::string key("paged:" + std::to_string(index));
             auto it = auxData.find(key);
             if (it != auxData.end()) {
-                return *(boost::any_cast<compression::PagedInputStream::Ptr>(it->second));
+                const std::pair<std::string, boost::any> &v = *it;
+                return *(boost::any_cast<compression::PagedInputStream::Ptr>(v.second));
             }
             else {
                 compression::PagedInputStream::Ptr pagedStream = std::make_shared<compression::PagedInputStream>();
```

**Comment by e4lam** [comment] 2022-07-28 14:20
@danrbailey I'm out of my depth at this point. I can't even seem to figure out how to narrow this in a way that and I submit a bug for and we want to move up to Visual Studio 2022 for next year's VFX Platform. The best thing so far I've come up with this is the hack in the previous comment. What do you think?

**Comment by Idclip** [comment] 2022-10-16 16:36
@danrbailey @e4lam this is still a problem right? We're building with `/permissive-` now but the CI is passing, presumably because we're not building with MSVC 2022. We should fix this before we release v10

**Comment by Idclip** [comment] 2022-10-16 16:42
Actually, just checked the job logs and looks like the github runners are running 2022?

https://github.com/AcademySoftwareFoundation/openvdb/actions/runs/3258602101/jobs/5350816908

But the builds are passing?

**Comment by e4lam** [comment] 2022-10-16 16:55
Yes, this should have been fixed with my last round of MSVC PRs #1460 and #1465 that were merged.

**Comment by Idclip** [comment] 2022-10-16 17:27
Awesome, thanks @e4lam - what was the fix for this issue in those PRs? My understanding was we could reproduce this error using VS 2022 with `/permissive-` which we are now doing. The other changes in these PRs are the addition of `Zc:inline`, `Zc:throwingNew` and the change in `Morphology.h`, but it's not clear what actually fixed it?

**Comment by e4lam** [comment] 2022-10-16 17:32
Sorry, I had a patch for this error specifically but I ended up throwing it out because it fixed itself with a newer VS2022 version. However, the newer VS2022 version then errored out in Morphology.h so I only ended up with an explicit patch for that.

**Comment by Idclip** [comment] 2022-10-16 17:43
Ah brilliant, that makes sense - thanks for confirming! In which case, for anyone else running into this issue, updating to the latest version of VS2022 should resolve this problem (and we now build with `/permissive-` by default to catch these issues in the future).

**Closed by Idclip** 2022-10-16 17:43 UTC
