### ISSUE TITLE
[BUG] unresolved external symbol imath_half_to_float_table error.

### ISSUE THREAD

**Issue by cgolchert** [AcademySoftwareFoundation/openvdb#1551] opened 2022-12-16 01:21 UTC
### Environment
Windows 10
10.0.0 through vcpkg
Visual Studio 2020 

### Describe the bug
Any function working on a grid will result in an unresolved external symbol imath_half_to_float_table error.
* Creating a grid will work
* getting the library version works. 

good ->  openvdb::FloatGrid::Ptr grid;
error -> openvdb::FloatGrid::Ptr grid = openvdb::FloatGrid::create();

### To Reproduce
1. Build with vcpkg
2. IN Visual Studio try to build the 'hello world' example from the cookbook
3. See error
4. Try using the various 'use imath half' or 'internal half' settings to either have nothing change or complain that openexr doesn't have a half.h file.

### Expected behavior
I expected it to work like before upgrading to v10. 

### Additional context
It seems like any time that the 'half' code is touched it breaks something with the windows build.  Searching for "unresolved external symbol imath_half_to_float_table" actually showed up on the openexr repository issues so it seems like it could be more than a bad openvdb build.

**Comment by cgolchert** [comment] 2022-12-16 01:29
[openvdb_vcpkg.log](https://github.com/AcademySoftwareFoundation/openvdb/files/10241932/openvdb_vcpkg.log)

vcpkg install  output for openvdb build

**Comment by cgolchert** [comment] 2022-12-16 01:55
#define IMATH_HALF_NO_LOOKUP_TABLE

..seems to have fixed the issue with the hello world.

**Comment by cgolchert** [comment] 2022-12-16 02:39
as a project preprocessor (not a specific #define)  IMATH_HALF_NO_LOOKUP_TABLE also seems to fix the error.

**Comment by Idclip** [comment] 2022-12-16 11:23
Hi,

> It seems like any time that the 'half' code is touched it breaks something with the windows build. 

We didn't touch the half implementation for 10.0.0. What changed was the added build system support to build against EXR/Imath 3.1.X. Looking at the vcpkg port of OpenVDB, it looks like the build is configured to build against the external installations of EXR and Imath 3.1.X, so you'll need to make sure you're linking to those libraries too. Can you verify this is happening? Defining `IMATH_HALF_NO_LOOKUP_TABLE` will cause the half implementation to not require the symbols from the Imath lib so this will of course also resolve your problem. But I suspect as soon as you try to use other symbols from EXR/Imath you'll run into similar issues

**Comment by cgolchert** [comment] 2022-12-16 18:39
Just woke up so I hope I'm answering what you asked..  I'm linking to the libraries that vcpkg baked out for the openvdb build.  The half error is the only one I've run into as I'm not using anything exr related myself.


It looks like I skipped the 9.x version and the 8.x was working with the previous exr/imath stuff.  That is what I meant about the half changes.  I just get nervous when there is a rush to blow through to the next new thing before the current is 100%  (PR for "dropping <3.1")

**Comment by Idclip** [comment] 2022-12-16 19:21
>  I'm linking to the libraries that vcpkg baked out for the openvdb build.

Are you able to provide the full verbose build log of your project?

> I just get nervous when there is a rush to blow through to the next new thing before the current is 100% 

There is no rush. Different projects deal with dependency transitions with different velocities. I like to believe we are careful and try to always provide enough of a transitional period between different versions.

For example, we still support building against EXR 2.4 whilst we transition to 3.1.X. We additionally support not even requiring EXR/IMath at all. You don't need it on your system. VDB comes bundled with a copy of the half implementation which the build uses by default (see `USE_EXR` and `USE_IMATH_HALF`). It is the vcpkg port's choice to opt to use the external copy of EXR 3.1.X:

https://github.com/microsoft/vcpkg/blob/master/ports/openvdb/portfile.cmake

All three options are supported and tested. There is no doubt issues will arise, and you may very well have uncovered one (though I cannot reproduce this), but we mitigate them as much as we can.

**Comment by Idclip** [comment] 2023-01-10 17:43
I will close this, but please re-open if you have not been able to resolve it and it's still an issue

**Closed by Idclip** 2023-01-10 17:43 UTC
Labels: bug
