### ISSUE TITLE
[INSTALL] 'second': is not a member of 'std::pair<const std::string,boost::any>'

### ISSUE THREAD

**Issue by wilkesreid** [AcademySoftwareFoundation/openvdb#1446] opened 2022-08-09 03:31 UTC
### Environment
**Operating System:** Windows 10
**Version / Commit SHA:** Release 9.1.0
**CMake Version:** 3.21.3
**Compiler:** MSVC2022

### Describe the problem
When attempting to #include <openvdb/openvdb.h>, I receive the error `'second': is not a member of 'std::pair<const std::string,boost::any>'` in PointDataGrid.h at lines 1175, 1219, 1341, 1353, 1377, 1382, 1396, and 1407.

### To Reproduce
1. Download and extract OpenVDB release 9.1.0
2. Follow the documented instructions for building and installing OpenVDB on Windows
3. Create a C++ source file and configure libraries/include directories, and add `#include <openvdb/openvdb.h>`
5. See error

**Comment by Idclip** [comment] 2022-10-16 16:38
Hey, thanks for reporting this - I think this is a duplicate of #1385, so closing in favour of that

**Closed by Idclip** 2022-10-16 16:38 UTC
