### ISSUE TITLE
[BUG] TestStreamCompression.testPagedStreams fails

### ISSUE THREAD

**Issue by yurivict** [AcademySoftwareFoundation/openvdb#1152] opened 2021-08-15 03:34 UTC
### Environment
**Operating System:** FreeBSD 13
**Version / Commit SHA:** VDB-8.1.0
**Other:** clang-11

### Describe the bug
```
[ RUN      ] TestStreamCompression.testPagedStreams
/disk-samsung/freebsd-ports/misc/openvdb/work/openvdb-8.1.0/openvdb/openvdb/unittest/TestStreamCompression.cc:422: Failure
Expected equality of these values:
  ss.tellp()
    Which is: 4452
  std::streampos(5400)
    Which is: 5400
/disk-samsung/freebsd-ports/misc/openvdb/work/openvdb-8.1.0/openvdb/openvdb/unittest/TestStreamCompression.cc:455: Failure
Expected equality of these values:
  ss.tellg()
    Which is: 4452
  std::streampos(5400)
    Which is: 5400
/disk-samsung/freebsd-ports/misc/openvdb/work/openvdb-8.1.0/openvdb/openvdb/unittest/TestStreamCompression.cc:548: Failure
Expected equality of these values:
  fileout.tellp()
    Which is: 42724
  std::streampos(51480)
    Which is: 51480
[  FAILED  ] TestStreamCompression.testPagedStreams (34 ms)
[----------] 2 tests from TestStreamCompression (35 ms total)
```

**Comment by Idclip** [comment] 2021-08-15 22:04
Duplicate of #1103. You're probably using an incompatible version of blosc, it's only recommended to use blosc 1.5.0.

**Closed by Idclip** 2021-08-15 22:04 UTC
Labels: bug
